.PHONY: mlton mlton-create-link mlton-clean

mlton-test:
	@echo Test building with mlton.
	mlton -verbose 1 MyLib.mlb
	@echo Remove the test build as it is not needed.
	-rm MyLib

.PHONY: mlton-create-link
mlton-create-link:
	@echo This is at your own risk.
	ln -s "`pwd`" /usr/lib/mlton/sml/

.PHONY: mlton-clean
mlton-clean:
	-rm MyLib
	-rm /usr/lib/mlton/sml/mylib
